2019-03-03 19:53:05,464 - python_logging.first_class - ERROR - Failed to open file
Traceback (most recent call last):
  File "/Users/gonsoomoon/Documents/DeepLearning/gan/practice/python_logging/first_class.py", line 29, in show_captue_exception
    open('/path/to/does/not/exist', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/does/not/exist'
